# lib/park.rb
class Park
  # Exposes name, admission_price, and vehicles as read-only attributes
  attr_reader :name, :admission_price, :vehicles

  # Constructor method to initialize a park with its name, admission price, and an empty array for vehicles
  def initialize(name, admission_price)
    @name = name                        # Stores the name of the park
    @admission_price = admission_price  # Stores the admission price (cost per adult)
    @vehicles = []                      # Initializes an empty array to track vehicles that enter the park
  end

  # Adds a vehicle to the list of vehicles in the park
  # This method receives a vehicle object and appends it to the @vehicles array
  def add_vehicle(vehicle)
    @vehicles << vehicle
  end

  # Gathers all passengers from all vehicles in the park
  # Uses flat_map to iterate over all vehicles and collect their passengers
  def passengers
    # flat_map ensures that we flatten the arrays of passengers from each vehicle into one array
    @vehicles.flat_map(&:passengers)
  end

  # Calculates the total revenue generated by the park
  # Revenue is calculated based on the number of adult passengers multiplied by the admission price
  def revenue
    # Counts the number of adult passengers and multiplies by the park's admission price
    total_adults = passengers.count { |passenger| passenger.adult? }
    total_adults * @admission_price
  end
end